apiVersion: v1
kind: PersistentVolume
metadata:
  name: fsx-openzfs-pv
spec:
  capacity:
    storage: 64Gi
  accessModes:
    - ReadWriteMany
  mountOptions:
    - nfsvers=4.1
    - rsize=1048576
    - wsize=1048576
    - timeo=600
  persistentVolumeReclaimPolicy: Delete
  csi:
    driver: fsx.openzfs.csi.aws.com
    volumeHandle: "<fs-id>"
    volumeAttributes:
      DNSName: "<fs-id>.fsx.<region>.amazonaws.com"
      ResourceType: "filesystem"
