apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fsx-openzfs-claim
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 64Gi
  volumeName: fsx-openzfs-pv
