apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: csi-s3-external-secret
spec:
  refreshInterval: 1m # rate SecretManager pulls GCPSM
  secretStoreRef:
    kind: SecretStore
    name: "csi-s3-secretstore" # name of the SecretStore (or kind specified)
  target:
    name: "csi-s3-secret"  # name of the k8s Secret to be created
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: {{.Values.secret.name}}  # aws secret