apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: csi-s3-secretstore
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.secret.awsRegion | quote }}
      auth:
        jwt:
          serviceAccountRef:
            name: {{ .Values.serviceAccount.name | quote }}
