apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: fsx-ontap-sc
provisioner: csi.trident.netapp.io
parameters:
  backendType: "ontap-nas"
  fsType: "ext4"
allowVolumeExpansion: True
reclaimPolicy: Delete
