apiVersion: v1
kind: Secret
metadata:
  name: fsx-ontap-secret
  namespace: trident
type: Opaque
stringData:
  username: fsxadmin
  password: secretpass123
---
apiVersion: trident.netapp.io/v1
kind: TridentBackendConfig
metadata:
  name: fsx-ontap-tbc
  namespace: trident
spec:
  version: 1
  storageDriverName: ontap-nas
  managementLIF: management.<fs-id>.fsx.<REGION>.amazonaws.com
  dataLIF: svm-<svm-id>.<fs-id>.fsx.<REGION>.amazonaws.com
  backendName: fsx-ontap
  svm: fsx
  credentials:
    name: fsx-ontap-secret
