name: test1

on: workflow_dispatch

permissions:
  id-token: write
  contents: read

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout helm repo
        uses: actions/checkout@v3
        with:
          repository: ''
          token: ${{ secrets.test1_secret }}
          ref: ''

      - name: Commit new helm chart version
        run: |
          git config user.name greatehop
          git config user.email greatehop@gmail.com
          git config --global credential.helper cache
          git checkout -b test1
          date > cur_date.txt
          git add cur_date.txt
          git commit -m "test1"
          git push origin test1
